service: serverless-webpack-boilerplate

frameworkVersion: ">=1.1.0 <2.0.0"

package:
  exclude:
    - .eslintrc.js
    - .gitattributes
    - .gitignore
    - .npmrc
    - .babelrc
    - README.md
    - serverless.yml
  include:
    - functions/**
    - config/**
    - core/**
    - package.json

custom:
  webpackIncludeModules: true

plugins:
  - serverless-webpack

provider:
  name: aws
  cfLogs: true
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  memorySize: 128

functions:
  function1:
    handler: function1.run
    events:
      - http:
          path: run1
          method: post
          cors: true

  function2:
    handler: function2.run
    events:
      - http:
          path: run2
          method: post
          cors: true

### yeoman hook ###
